### ISSUE TITLE
too few arguments in function call

### ISSUE THREAD

**Issue by zjin-lcf** [albertozeni/LOGAN#1]
nvcc -arch=sm_70 -O3 -maxrregcount=32 -std=c++11 -Xcompiler -fopenmp demo.cu -o demo -D ADAPTABLE
demo.cu(134): error: too few arguments in function call

Thanks for your fix.

May you please tell how a user can verify the GPU result ?   

Thanks

**Comment by zjin-lcf** [comment]
417 inline void extendSeedL(vector<SeedL> &seeds,
418       ExtensionDirectionL direction,
419       vector<string> &target,
420       vector<string> &query,
421       vector<ScoringSchemeL> &penalties,
422       int const& XDrop,
423       int const& kmer_length,
424       int *res,
425       int numAlignments,
426       int ngpus,
427       int n_threads 
428       // long int cups
429       )

That may solve the issue

**Comment by albertozeni** [comment]
hi, let me look into that, I just saw the issue

**Comment by albertozeni** [comment]
Ok, I saw where the error is, some parts of the code where updated without updating other parts, I will fix the code asap, the GCUPS computation basically broke the code. Also regarding the correctness of the alignments, our software performs the same exact alignment as the XDROP function present in seqan.

**Comment by albertozeni** [comment]
There is a version of the software on the repo that runs both alignments (GPU and SeqAn) and tests correctness, I will update the readme.

**Comment by zjin-lcf** [comment]
Okay. I noticed that you measure the data transfer time for the cuda function 'memcpyAsync'. I recall that it is asynchronous memory copy. 

Thanks for your updates!

**Comment by albertozeni** [comment]
Hi, code fixed. The transfer time measuring remained like that since the first version of the code when I was still using  synchronous memory transfers, when I switched to asynchronous transfers I used that metric to see how much overhead it was to malloc the variables instead of pinning the memory. I just left it there even though it is not technically correct to call it transfer time. The time that we show on the README comprehend all the time spent by the software to setup inputs, transfer and run on GPU, not only the GPU compute time so don't worry about those times.
