### ISSUE TITLE
Seqan free version

### ISSUE THREAD

**Issue by armintoepfer** [albertozeni/LOGAN#3]
Hi!

Is there any chance to provide a seqan free version? I'd love to use it, but I don't want to add seqan, as it's intrusive and code hog.

Thank you!
Armin

**Comment by albertozeni** [comment]
Hi Armin,

I think the version inserted in the demo is already seqan free.
Anyway, I will update a new version without seqan dependencies over the weekend if the current one still requires seqan. 
Thank you for suggesting this update,

Best,
Alberto

**Comment by armintoepfer** [comment]
Amazing. Thank you!

**Comment by armintoepfer** [comment]
Me again. I think I misunderstood your library initially. I want to pairwise align sequences and get the base alignment. Is that possible, either directly or by computing the Viterbi path on my own?

**Comment by albertozeni** [comment]
Hi Armin,
do you want to align sequences without using the seeds or do you want to compute them on your own?
Also, I checked the repo and the library does not require seqan to build, so that problem solved itself.
If you want to continue this conversation I think that It might be easier to continue chatting via email: alberto.zeni@mail.polimi.it
